# Generated by Django 4.1 on 2022-08-30 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("oc_lettings_site", "0004_alter_profile_user"),
        ("profiles", "0002_auto_20220830_1453"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Profile",
        ),
    ]
